import pandas as pd
import random


def convert_csv_to_txt(input_file, output_file):
    # 尝试不同的编码格式读取 CSV 文件
    try:
        # 首先尝试 UTF-8 编码
        df = pd.read_csv(input_file, encoding='utf-8')
    except UnicodeDecodeError:
        try:
            # 如果 UTF-8 失败，尝试 GBK 编码（常用于中文 Windows 系统）
            df = pd.read_csv(input_file, encoding='gbk')
        except UnicodeDecodeError:
            try:
                # 再尝试 GB18030（GBK 的超集，支持更多中文字符）
                df = pd.read_csv(input_file, encoding='gb18030')
            except UnicodeDecodeError:
                # 最后尝试 latin1（几乎可以解码任何文件，但可能会有乱码）
                df = pd.read_csv(input_file, encoding='latin1')

    sentence_templates = [
        # 模板1
        lambda a, b, c, d: f"在{a}作业时，若存在{b}，可能引发{c}，需通过{d}进行有效预防",
        # 模板2
        lambda a, b, c, d: f"针对{a}的{b}问题，为避免{c}风险，必须严格执行{d}",
        # 模板3
        lambda a, b, c, d: f"{a}区域因{b}未被管控，易导致{c}，日常应落实{d}以消除隐患",
        # 模板4
        lambda a, b, c, d: f"为降低{a}中{b}引发的{c}概率，需优先实施{d}",
        # 模板5
        lambda a, b, c, d: f"若{a}的{b}未及时整改，可能升级为{c}，应通过{d}提前干预",
        # 模板6
        lambda a, b, c, d: f"在{a}排查时发现{b}，应立即采取{d}，防止{c}发生",
        # 模板7
        lambda a, b, c, d: f"{a}的{b}是{c}的主要诱因，需通过{d}从源头遏制风险",
        # 模板8
        lambda a, b, c, d: f"针对{a}出现的{b}，为防范{c}，需常态化执行{d}",
        # 模板9
        lambda a, b, c, d: f"{a}作业前，应对{b}进行全面检查，并落实{d}以规避{c}。",
        # 模板10
        lambda a, b, c, d: f"因{a}的{b}存在隐蔽性，需通过{d}主动预防，避免{c}突发"
    ]

    # 以 UTF-8 编码写入输出文件
    with open(output_file, 'w', encoding='utf-8') as f:
        # 处理第二行开始的每一行（跳过标题行）
        # 处理从第二行开始的每一行
        for i, row in df.iloc[1:].iterrows():
            # 提取各列的值
            col_A = row.iloc[0]  # 施工位置
            col_B = row.iloc[1]  # 危险源
            col_C = row.iloc[2]  # 潜在风险
            col_D = row.iloc[3]  # 预防措施

            # 随机选择一个句式模板
            template = random.choice(sentence_templates)

            # 使用选择的模板创建句子
            sentence = template(col_A, col_B, col_C, col_D)


            # 写入句子到文件
            f.write(sentence + '\n')

    print(f"成功将 CSV 转换为 TXT。输出保存到 {output_file}")



# Example usage
if __name__ == "__main__":
    input_file = "风险防控.csv"  # The CSV file generated by the previous script
    output_file = "风险防控.txt"  # The output TXT file
    convert_csv_to_txt(input_file, output_file)
