import pandas as pd
import random


def convert_csv_to_txt(input_file, output_file):
    # 尝试不同的编码格式读取 CSV 文件
    try:
        # 首先尝试 UTF-8 编码
        df = pd.read_csv(input_file, encoding='utf-8')
    except UnicodeDecodeError:
        try:
            # 如果 UTF-8 失败，尝试 GBK 编码（常用于中文 Windows 系统）
            df = pd.read_csv(input_file, encoding='gbk')
        except UnicodeDecodeError:
            try:
                # 再尝试 GB18030（GBK 的超集，支持更多中文字符）
                df = pd.read_csv(input_file, encoding='gb18030')
            except UnicodeDecodeError:
                # 最后尝试 latin1（几乎可以解码任何文件，但可能会有乱码）
                df = pd.read_csv(input_file, encoding='latin1')

    sentence_templates = [
        # 原始模板
        lambda a, b, c, d, e: f"对于{a}的{b}，在进行{c}的{d}工作时，{e}",
        # 新增模板1
        lambda a, b, c, d, e: f"在{a}施工区域的{b}，执行{c}{d}操作期间，需要{e}",
        # 新增模板2
        lambda a, b, c, d, e: f"{a}的{b}区域内，当开展{c}的{d}施工环节时，应当{e}",
        # 新增模板3
        lambda a, b, c, d, e: f"针对{b}中的{a}，实施{c}{d}作业过程中，必须{e}",
        # 新增模板4
        lambda a, b, c, d, e: f"{a}的{b}位置，在{c}{d}施工阶段，要求{e}"
    ]

    # 以 UTF-8 编码写入输出文件
    with open(output_file, 'w', encoding='utf-8') as f:
        # 处理第二行开始的每一行（跳过标题行）
        # 处理从第二行开始的每一行
        for i, row in df.iloc[1:].iterrows():
            # 提取各列的值
            col_A = row.iloc[0]  # 施工位置
            col_B = row.iloc[1]  # 施工位置
            col_C = row.iloc[2]  # 施工活动
            col_D = row.iloc[3]  # 施工工序
            col_E = row.iloc[4]  # 作业要求

            # 随机选择一个句式模板
            template = random.choice(sentence_templates)

            # 使用选择的模板创建句子
            sentence = template(col_A, col_B, col_C, col_D, col_E)


            # 写入句子到文件
            f.write(sentence + '\n')

    print(f"成功将 CSV 转换为 TXT。输出保存到 {output_file}")



# Example usage
if __name__ == "__main__":
    input_file = "作业控制.csv"  # The CSV file generated by the previous script
    output_file = "作业控制.txt"  # The output TXT file
    convert_csv_to_txt(input_file, output_file)
