import pandas as pd
import random


def convert_csv_to_txt(input_file, output_file):
    # 尝试不同的编码格式读取 CSV 文件
    try:
        # 首先尝试 UTF-8 编码
        df = pd.read_csv(input_file, encoding='utf-8')
    except UnicodeDecodeError:
        try:
            # 如果 UTF-8 失败，尝试 GBK 编码（常用于中文 Windows 系统）
            df = pd.read_csv(input_file, encoding='gbk')
        except UnicodeDecodeError:
            try:
                # 再尝试 GB18030（GBK 的超集，支持更多中文字符）
                df = pd.read_csv(input_file, encoding='gb18030')
            except UnicodeDecodeError:
                # 最后尝试 latin1（几乎可以解码任何文件，但可能会有乱码）
                df = pd.read_csv(input_file, encoding='latin1')

    sentence_templates = [
        # 模板1
        lambda a, b, c, d, e: f"在{a}的{b}区域，因{c}可能引发{d}时，应立即{e}",
        # 模板2
        lambda a, b, c, d, e: f"针对{a}中存在的{b}，为避免{c}升级为{d}，需严格执行{e}",
        # 模板3
        lambda a, b, c, d, e: f"若{a}的{b}未被有效管控，将导致{c}并触发{d}，此时应迅速{e}",
        # 模板4
        lambda a, b, c, d, e: f"{a}内因{b}产生的{c}，一旦发展为{d}，必须优先采取{e}",
        # 模板5
        lambda a, b, c, d, e: f"为预防{a}的{b}引发{c}及{d}，作业前应落实{e}",
        # 模板6
        lambda a, b, c, d, e: f"当{a}发生{b}相关的{c}并出现{d}时，需按预案{e}",
        # 模板7
        lambda a, b, c, d, e: f"{a}中{b}若未及时处理，可能因{c}造成{d}，需立即{e}",
        # 模板8
        lambda a, b, c, d, e: f"在{a}排查{b}时，若发现{c}可能导致{d}，应提前部署{e}",
        # 模板9
        lambda a, b, c, d, e: f"{a}的{b}管理失控会加剧{c}，最终引发{d}，此时需紧急{e}",
        # 模板10
        lambda a, b, c, d, e: f"针对{a}内{b}导致的{c}和{d}，必须按照{e}开展救援"
    ]

    # 以 UTF-8 编码写入输出文件
    with open(output_file, 'w', encoding='utf-8') as f:
        # 处理第二行开始的每一行（跳过标题行）
        # 处理从第二行开始的每一行
        for i, row in df.iloc[1:].iterrows():
            # 提取各列的值
            col_A = row.iloc[0]  # 施工位置
            col_B = row.iloc[1]  # 危险源
            col_C = row.iloc[2]  # 潜在风险
            col_D = row.iloc[3]  # 事故类型
            col_E = row.iloc[4]  # 处置措施

            # 随机选择一个句式模板
            template = random.choice(sentence_templates)

            # 使用选择的模板创建句子
            sentence = template(col_A, col_B, col_C, col_D, col_E)


            # 写入句子到文件
            f.write(sentence + '\n')

    print(f"成功将 CSV 转换为 TXT。输出保存到 {output_file}")



# Example usage
if __name__ == "__main__":
    input_file = "应急处置.csv"  # The CSV file generated by the previous script
    output_file = "应急处置.txt"  # The output TXT file
    convert_csv_to_txt(input_file, output_file)